//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SuperProcessManager.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_PUBLICTEXTBAR               101
#define IDC_NETWORKDATA_LIST            102
#define IDR_MAINFRAME                   128
#define IDR_SUPERPTYPE                  129
#define IDD_PROCESS_NETWORKIO_DLG       132
#define IDR_PROCESS_LIST_MENU           132
#define IDD_PROCESS_MANAGER_DLG         133
#define IDD_PROCESS_FILEIO_DLG          134
#define IDD_PROCESS_REGIO_DLG           135
#define IDD_TEXTBAR_DLG                 136
#define IDR_NETWORK_IO_DATA_LIST_MENU   137
#define IDD_NETWORK_SETTING_DLG         138
#define IDB_ABOUT_BG                    138
#define IDD_MONITOR_NETWORKIO_SETTING_DLG 138
#define IDD_RUNLOG_DLG                  139
#define IDR_NOTIFYICON_MENU             139
#define IDD_MONITOR_FILE                140
#define IDD_LISTCTRL_FILTER_DLG         142
#define IDC_PROCESS_LIST                1000
#define IDC_COMBO_ADDRESS               1001
#define IDC_DATA_LIST                   1003
#define IDC_LOG_LIST                    1004
#define IDC_HEX_TEXT                    1005
#define IDC_MYSAY                       1006
#define IDC_ASCII_TEXT                  1007
#define IDC_FILE_PATH                   1007
#define IDC_BROWSER_FILE                1008
#define IDC_COMMAN_LINE                 1009
#define IDC_WORK_DIRECTORY              1010
#define IDC_BROWSER_DIR                 1011
#define IDC_HIDE_RUN                    1012
#define IDC_SHOW_RUN                    1013
#define IDC_DESKTOP                     1014
#define IDC_MONITOR_TAGERT              1015
#define IDC_MONITOR_NETWORKIO           1016
#define IDC_MONITOR_FILEIO              1017
#define IDC_MONITOR_REGIO               1018
#define IDC_SWITCH_NETWORKMONITRO       1019
#define IDC_SWITCH_FILEMONITRO          1020
#define IDC_COMBO_COLUMN                1020
#define IDC_SWITCH_REGMONITRO           1021
#define IDC_COMBO_RULE                  1021
#define IDC_OK                          1022
#define IDC_DONE                        1022
#define IDC_PARAMETER_TEXT              1022
#define IDC_OPERATE_SELECT              1024
#define IDC_OPERATE_DELETE              1025
#define IDC_RESULT_TEXT                 1026
#define IDC_LIST                        1027
#define IDC_HOOK_SEND                   1028
#define IDC_HOOK_WSASEND                1029
#define IDC_HOOK_RECV                   1030
#define IDC_HOOK_WSARECV                1031
#define IDC_HOOK_SENDTO                 1032
#define IDC_HOOK_WSASENDTO              1033
#define IDC_HOOK_RECVFROM               1034
#define IDC_HOOK_WSARECVFROM            1035
#define IDM_TERMINATOR_PROCESS_CUREENT  32771
#define IDM_TERMINATOR_PROCESS_CHECKBOX 32772
#define IDM_TERMINATOR_PROCESS_TREE     32773
#define IDM_DEBUG_PROCESS               32774
#define IDM_SET_PRIORITY_REALTIME       32775
#define IDM_SET_PRIORITY_HEIGHT         32776
#define IDM_SET_PRIORITY_ABOVE_HEIGHT   32777
#define IDM_SET_PRIORITY_NORMAL         32778
#define IDM_SET_PRIORITY_BELOW_NORMAL   32779
#define IDM_DELETE_SELECED              32779
#define IDM_SET_PRIORITY_IDEL           32780
#define IDM_DELETE_CURRENT              32780
#define IDM_SELECT_ALL                  32781
#define IDM_PROCESS_MODULE              32782
#define IDM_SELECT_REVERSE_ALL          32782
#define IDM_PROCESS_THREAD              32783
#define IDM_CANCEL_ALL                  32783
#define IDM_PROCESS_HANDLE              32784
#define IDM_SUSPPED_PROCESS             32785
#define IDM_POSITIONING_FILE            32788
#define IDM_ATTRIBUTE_FILE              32789
#define IDM_PUBLIC_TEXT_BAR             32790
#define IDM_MONITOR_NETWOKIO            32791
#define IDM_MONITOR_FILEIO              32792
#define IDM_MONITOR_REGIO               32793
#define IDM_MONITOR_ALL                 32794
#define IDM_GOOGLE_SEARCH               32795
#define IDM_BAIDU_SEARCH                32796
#define IDM_ONLINE_VIRUS_SCAN           32797
#define IDM_ABOUT                       32798
#define IDM_EXIT                        32799
#define IDM_SETTING                     32800
#define IDM_SHOW_WINDOW                 32801
#define IDM_TOPMOST                     32802
#define IDM_UPDATE                      32803
#define IDM_OPEN_IP                     32804
#define IDM_OPEN_DNS                    32805
#define IDM_BAIDU_SEARCH_IP             32806
#define IDM_GOOGLE_SEARCH_IP            32807
#define IDM_BAIDU_SEARCH_DNS            32808
#define IDM_GOOGLE_SEARCH_DNS           32809
#define IDM_MONITOR_NETWORKIO_SETTING   32810
#define IDM_DELETE_INVALID_DATA         32811
#define IDM_MONITOR_FILE                32812
#define IDM_TERMENATER_PROCESS          32813
#define IDM_SUSPEND_PROCESS             32814
#define IDM_RESUME_PROCESS              32815
#define IDM_FILTER                      32816
#define IDM_INJECT_PROCESS              32817
#define IDS_PROCESS_NUM                 61204
#define IDS_THREAD_NUM                  61205
#define IDS_CPU_USAGE                   61206
#define IDS_PAGEFILE_USAGE              61207
#define IDS_CPU_NUM                     61208
#define IDS_HANDLE_NUM                  61209

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
